In [4]:
import numpy as np
lst1=[1,2,3]
array1=np.array(lst1)
array1


array([1, 2, 3])

In [5]:
type(lst1)


list

In [6]:
type(array1)

numpy.ndarray

##perform mathematical operations on these datasets-Multiplication,Division

In [7]:
list2=[3,2,1]
array2=np.array(list2)
array2

array([3, 2, 1])

In [8]:
print("array2 multiplied by array1:",array1*array2)
print("array2 divided by array1:",array2/array1)
print("array2 raised to the power of array1:",array2**array1)
print(f"{array2}raised to the power of {array1}:,{array2**array1}")

array2 multiplied by array1: [3 4 3]
array2 divided by array1: [3.         1.         0.33333333]
array2 raised to the power of array1: [3 4 1]
[3 2 1]raised to the power of [1 2 3]:,[3 4 1]
